#ifndef RUNNER_D_CODE_ADDRESSES
#define RUNNER_D_CODE_ADDRESSES

#define runner_d_start_task_initialization_task		(0x14)
#define runner_d_initialization_task		(0x14)
#define runner_d_start_task_timer_scheduler_set		(0x1BC8)
#define runner_d_timer_scheduler_set		(0x1BC8)
#define runner_d_start_task_flow_cache_wakeup_request		(0xD84)
#define runner_d_flow_cache_wakeup_request		(0xD84)
#define runner_d_start_task_lan_dispatch_wakeup_request		(0x19A8)
#define runner_d_lan_dispatch_wakeup_request		(0x19A8)
#define runner_d_start_task_lan_cpu_wakeup_request		(0x154)
#define runner_d_lan_cpu_wakeup_request		(0x154)
#define runner_d_start_task_lan_normal_wakeup_request		(0x19C)
#define runner_d_lan_normal_wakeup_request		(0x19C)
#define runner_d_start_task_debug_routine		(0x6C)
#define runner_d_debug_routine		(0x6C)
#define runner_d_start_task_free_skb_index_wakeup_request		(0x1D44)
#define runner_d_free_skb_index_wakeup_request		(0x1D44)
#define runner_d_free_skb_index_tx_abs_done		(0x1D44)
#define runner_d_start_task_dhd_rx_complete_wakeup_request		(0x1EAC)
#define runner_d_dhd_rx_complete_wakeup_request		(0x1EAC)
#define runner_d_gpe_sop_push_replace_ddr_sram_32		(0x1364)
#define runner_d_gpe_sop_push_replace_sram_32_64		(0x13D4)
#define runner_d_gpe_sop_push_replace_sram_64		(0x13E8)
#define runner_d_gpe_sop_push_replace_sram_64_32		(0x13FC)
#define runner_d_gpe_sop_pull_replace_ddr_sram_32		(0x1410)
#define runner_d_gpe_sop_pull_replace_sram_32_64		(0x1480)
#define runner_d_gpe_sop_pull_replace_sram_64		(0x14D0)
#define runner_d_gpe_sop_pull_replace_sram_64_32		(0x150C)
#define runner_d_gpe_replace_pointer_32_ddr		(0x155C)
#define runner_d_gpe_replace_pointer_32_sram		(0x1580)
#define runner_d_gpe_replace_pointer_64_sram		(0x15A4)
#define runner_d_gpe_replace_16		(0x15C8)
#define runner_d_gpe_replace_32		(0x15FC)
#define runner_d_gpe_replace_bits_16		(0x1620)
#define runner_d_gpe_copy_add_16_cl		(0x164C)
#define runner_d_gpe_copy_add_16_sram		(0x1658)
#define runner_d_gpe_copy_bits_16_cl		(0x16A0)
#define runner_d_gpe_copy_bits_16_sram		(0x16AC)
#define runner_d_gpe_insert_16		(0x16F4)
#define runner_d_gpe_delete_16		(0x175C)
#define runner_d_gpe_decrement_8		(0x179C)
#define runner_d_gpe_apply_icsum_16		(0x17C0)
#define runner_d_gpe_apply_icsum_nz_16		(0x17E4)
#define runner_d_gpe_compute_csum_16_cl		(0x1820)
#define runner_d_gpe_compute_csum_16_sram		(0x182C)
#define runner_d_gpe_buffer_copy_16_sram		(0x186C)
#define runner_d_gpe_buffer_copy_16_ddr		(0x1894)
#define runner_d_upstream_ingress_rate_limiter_budget_allocate		(0x1C48)
#define runner_d_upstream_quasi_budget_allocate		(0x1CC8)
#define runner_d_schedule_free_skb_index		(0x1D28)

#endif
