/* IMAGE 0 LABELS */
#ifndef IMAGE_0_CODE_ADDRESSES
#define IMAGE_0_CODE_ADDRESSES

#define image_0_start_task_initialization_task        (0x58)
#define image_0_initialization_task        (0x58)
#define image_0_start_task_update_fifo_ds_read_1st_wakeup_request        (0x12d0)
#define image_0_update_fifo_ds_read_1st_wakeup_request        (0x12d0)
#define image_0_start_task_ghost_reporting_1st_wakeup_request        (0xd9c)
#define image_0_ghost_reporting_1st_wakeup_request        (0xd9c)
#define image_0_start_task_budget_allocator_1st_wakeup_request        (0x638)
#define image_0_budget_allocator_1st_wakeup_request        (0x638)
#define image_0_start_task_debug_routine        (0x98)
#define image_0_debug_routine        (0x98)
#define image_0_start_task_ds_tx_task_wakeup_request        (0x184)
#define image_0_ds_tx_task_wakeup_request        (0x184)
#define image_0_start_task_flush_task_1st_wakeup_request        (0xc94)
#define image_0_flush_task_1st_wakeup_request        (0xc94)
#define image_0_debug_routine_handler        (0xc)
#define image_0_ds_tx_scheduling_update_status        (0x430)
#define image_0_ds_tx_scheduling_action_not_valid        (0x4b0)
#define image_0_complex_scheduler_update_dwrr_basic_schedulers        (0x608)
#define image_0_complex_scheduler_update_dwrr_complex_schedulers        (0x618)
#define image_0_complex_scheduler_update_dwrr_queues        (0x628)
#define image_0_basic_rate_limiter_complex_scheduler        (0x94c)
#define image_0_basic_rate_limiter_basic_scheduler_no_cs        (0x984)
#define image_0_basic_rate_limiter_queue_with_cs_bs        (0x9b8)
#define image_0_basic_rate_limiter_queue_with_bs        (0xa0c)
#define image_0_complex_rate_limiter_queue_sir        (0xa48)
#define image_0_complex_rate_limiter_queue_pir        (0xa84)
#define image_0_complex_rate_limiter_basic_scheduler_sir        (0xac0)
#define image_0_complex_rate_limiter_basic_scheduler_pir        (0xafc)
#define image_0_basic_scheduler_update_dwrr        (0xbd4)

#endif

/* IMAGE 1 LABELS */
#ifndef IMAGE_1_CODE_ADDRESSES
#define IMAGE_1_CODE_ADDRESSES

#define image_1_start_task_initialization_task        (0x18)
#define image_1_initialization_task        (0x18)
#define image_1_start_task_processing_wakeup_request        (0xe3c)
#define image_1_processing_wakeup_request        (0xe3c)
#define image_1_start_task_debug_routine        (0x4e1c)
#define image_1_debug_routine        (0x4e1c)
#define image_1_start_task_cpu_rx_wakeup_request        (0x5c9c)
#define image_1_cpu_rx_wakeup_request        (0x5c9c)
#define image_1_start_task_cpu_recycle_wakeup_request        (0x6778)
#define image_1_cpu_recycle_wakeup_request        (0x6778)
#define image_1_start_task_interrupt_coalescing_1st_wakeup_request        (0x68cc)
#define image_1_interrupt_coalescing_1st_wakeup_request        (0x68cc)
#define image_1_tmp8        (0x63c8)
#define image_1_info_string0        (0x63c8)
#define image_1_info_string1        (0x63c8)
#define image_1_info_string2        (0x63c8)
#define image_1_info_string3        (0x63c8)
#define image_1_info_string4        (0x63c8)
#define image_1_info_string5        (0x63c8)
#define image_1_info_string6        (0x63c8)
#define image_1_section_abbrev        (0x63c8)
#define image_1_section_info        (0x63c8)
#define image_1_cu_begin0        (0x63c8)
#define image_1_debug_range        (0x63c8)
#define image_1_debug_ranges0        (0x63c8)
#define image_1_debug_macinfo        (0x63c8)
#define image_1_cu_macro_begin0        (0x63c8)
#define image_1_line_table_start0        (0x63c8)
#define image_1_start_task_cpu_rx_meter_budget_allocator_1st_wakeup_request        (0x63c8)
#define image_1_cpu_rx_meter_budget_allocator_1st_wakeup_request        (0x63c8)
#define image_1_start_task_cpu_rx_copy_wakeup_request        (0x4f48)
#define image_1_cpu_rx_copy_wakeup_request        (0x4f48)
#define image_1_start_task_spdsvc_gen_wakeup_request        (0x6990)
#define image_1_spdsvc_gen_wakeup_request        (0x6990)
#define image_1_start_task_common_reprocessing_wakeup_request        (0x7728)
#define image_1_common_reprocessing_wakeup_request        (0x7728)
#define image_1_c_cpu_rx_task        (0x5fb0)
#define image_1_func_begin0        (0x5fb0)
#define image_1_start_task_c_cpu_rx_wakeup_request        (0x5fb0)
#define image_1_c_cpu_rx_wakeup_request        (0x5fb0)
#define image_1_debug_routine_handler        (0xc)
#define image_1_action_exception        (0x58)
#define image_1_processing_header_update_length_calc        (0x2a14)
#define image_1_processing_layer2_header_copy_30_bytes_8_bytes_align        (0x2ad8)
#define image_1_processing_layer2_header_copy_22_bytes_8_bytes_align        (0x2ae0)
#define image_1_processing_layer2_header_copy_14_bytes_8_bytes_align        (0x2ae8)
#define image_1_processing_layer2_header_copy_30_bytes_4_bytes_align        (0x2afc)
#define image_1_processing_layer2_header_copy_22_bytes_4_bytes_align        (0x2b0c)
#define image_1_processing_layer2_header_copy_14_bytes_4_bytes_align        (0x2b1c)
#define image_1_processing_layer2_header_copy_26_bytes_8_bytes_align        (0x2b3c)
#define image_1_processing_layer2_header_copy_18_bytes_8_bytes_align        (0x2b48)
#define image_1_processing_layer2_header_copy_18_bytes_4_bytes_align        (0x2b6c)
#define image_1_processing_layer2_header_copy_26_bytes_4_bytes_align        (0x2b78)
#define image_1_tcam_cmd_ic_submit        (0x3b94)
#define image_1_tcam_cmd_outer_tpid        (0x3bd8)
#define image_1_tcam_cmd_inner_tpid        (0x3bf0)
#define image_1_tcam_cmd_ethertype        (0x3c08)
#define image_1_tcam_cmd_outer_vid        (0x3c20)
#define image_1_tcam_cmd_inner_vid        (0x3c38)
#define image_1_tcam_cmd_outer_pbit        (0x3c50)
#define image_1_tcam_cmd_inner_pbit        (0x3c68)
#define image_1_tcam_cmd_vlan_num        (0x3c80)
#define image_1_tcam_cmd_ip_protocol        (0x3c98)
#define image_1_tcam_cmd_l3_protocol        (0x3cb0)
#define image_1_tcam_cmd_tos        (0x3cc8)
#define image_1_tcam_cmd_network_layer        (0x3ce0)
#define image_1_tcam_cmd_ingress_port        (0x3d00)
#define image_1_tcam_cmd_gem_flow        (0x3d18)
#define image_1_tcam_cmd_ipv6_label        (0x3d30)
#define image_1_tcam_cmd_src_ip        (0x3d5c)
#define image_1_tcam_cmd_src_ipv6_masked        (0x3db0)
#define image_1_tcam_cmd_dst_ip        (0x3de4)
#define image_1_tcam_cmd_dst_ipv6_masked        (0x3e38)
#define image_1_tcam_cmd_src_port        (0x3e6c)
#define image_1_tcam_cmd_dst_port        (0x3e84)
#define image_1_tcam_cmd_src_mac        (0x3e9c)
#define image_1_tcam_cmd_dst_mac        (0x3ec8)
#define image_1_tcam_cmd_generic_l2        (0x3ef4)
#define image_1_tcam_cmd_generic_l3        (0x3f28)
#define image_1_tcam_cmd_generic_l4        (0x3f5c)
#define image_1_gpe_cmd_replace_16        (0x4500)
#define image_1_gpe_cmd_replace_32        (0x4508)
#define image_1_gpe_cmd_replace_bits_16        (0x4520)
#define image_1_gpe_cmd_copy_bits_16        (0x4540)
#define image_1_gpe_cmd_skip_if        (0x4570)
#define image_1_gpe_vlan_action_cmd_drop        (0x4590)
#define image_1_gpe_vlan_action_cmd_dscp        (0x4594)
#define image_1_gpe_vlan_action_cmd_mac_hdr_copy        (0x45e4)

#endif

/* IMAGE 2 LABELS */
#ifndef IMAGE_2_CODE_ADDRESSES
#define IMAGE_2_CODE_ADDRESSES

#define image_2_start_task_initialization_task        (0x18)
#define image_2_initialization_task        (0x18)
#define image_2_start_task_processing_wakeup_request        (0xf68)
#define image_2_processing_wakeup_request        (0xf68)
#define image_2_start_task_cpu_tx_wakeup_request        (0x4f48)
#define image_2_cpu_tx_wakeup_request        (0x4f48)
#define image_2_cpu_tx_read_ring_indices        (0x4f48)
#define image_2_start_task_debug_routine        (0x58)
#define image_2_debug_routine        (0x58)
#define image_2_start_task_cpu_recycle_wakeup_request        (0x55c4)
#define image_2_cpu_recycle_wakeup_request        (0x55c4)
#define image_2_start_task_interrupt_coalescing_1st_wakeup_request        (0x5b3c)
#define image_2_interrupt_coalescing_1st_wakeup_request        (0x5b3c)
#define image_2_start_task_timer_common_task_wakeup_request        (0x5718)
#define image_2_timer_common_task_wakeup_request        (0x5718)
#define image_2_debug_routine_handler        (0xc)
#define image_2_action_exception        (0x184)
#define image_2_processing_header_update_length_calc        (0x2b40)
#define image_2_processing_layer2_header_copy_30_bytes_8_bytes_align        (0x2c04)
#define image_2_processing_layer2_header_copy_22_bytes_8_bytes_align        (0x2c0c)
#define image_2_processing_layer2_header_copy_14_bytes_8_bytes_align        (0x2c14)
#define image_2_processing_layer2_header_copy_30_bytes_4_bytes_align        (0x2c28)
#define image_2_processing_layer2_header_copy_22_bytes_4_bytes_align        (0x2c38)
#define image_2_processing_layer2_header_copy_14_bytes_4_bytes_align        (0x2c48)
#define image_2_processing_layer2_header_copy_26_bytes_8_bytes_align        (0x2c68)
#define image_2_processing_layer2_header_copy_18_bytes_8_bytes_align        (0x2c74)
#define image_2_processing_layer2_header_copy_18_bytes_4_bytes_align        (0x2c98)
#define image_2_processing_layer2_header_copy_26_bytes_4_bytes_align        (0x2ca4)
#define image_2_tcam_cmd_ic_submit        (0x3cc0)
#define image_2_tcam_cmd_outer_tpid        (0x3d04)
#define image_2_tcam_cmd_inner_tpid        (0x3d1c)
#define image_2_tcam_cmd_ethertype        (0x3d34)
#define image_2_tcam_cmd_outer_vid        (0x3d4c)
#define image_2_tcam_cmd_inner_vid        (0x3d64)
#define image_2_tcam_cmd_outer_pbit        (0x3d7c)
#define image_2_tcam_cmd_inner_pbit        (0x3d94)
#define image_2_tcam_cmd_vlan_num        (0x3dac)
#define image_2_tcam_cmd_ip_protocol        (0x3dc4)
#define image_2_tcam_cmd_l3_protocol        (0x3ddc)
#define image_2_tcam_cmd_tos        (0x3df4)
#define image_2_tcam_cmd_network_layer        (0x3e0c)
#define image_2_tcam_cmd_ingress_port        (0x3e2c)
#define image_2_tcam_cmd_gem_flow        (0x3e44)
#define image_2_tcam_cmd_ipv6_label        (0x3e5c)
#define image_2_tcam_cmd_src_ip        (0x3e88)
#define image_2_tcam_cmd_src_ipv6_masked        (0x3edc)
#define image_2_tcam_cmd_dst_ip        (0x3f10)
#define image_2_tcam_cmd_dst_ipv6_masked        (0x3f64)
#define image_2_tcam_cmd_src_port        (0x3f98)
#define image_2_tcam_cmd_dst_port        (0x3fb0)
#define image_2_tcam_cmd_src_mac        (0x3fc8)
#define image_2_tcam_cmd_dst_mac        (0x3ff4)
#define image_2_tcam_cmd_generic_l2        (0x4020)
#define image_2_tcam_cmd_generic_l3        (0x4054)
#define image_2_tcam_cmd_generic_l4        (0x4088)
#define image_2_gpe_cmd_replace_16        (0x462c)
#define image_2_gpe_cmd_replace_32        (0x4634)
#define image_2_gpe_cmd_replace_bits_16        (0x464c)
#define image_2_gpe_cmd_copy_bits_16        (0x466c)
#define image_2_gpe_cmd_skip_if        (0x469c)
#define image_2_gpe_vlan_action_cmd_drop        (0x46bc)
#define image_2_gpe_vlan_action_cmd_dscp        (0x46c0)
#define image_2_gpe_vlan_action_cmd_mac_hdr_copy        (0x4710)

#endif

/* IMAGE 3 LABELS */
#ifndef IMAGE_3_CODE_ADDRESSES
#define IMAGE_3_CODE_ADDRESSES

#define image_3_start_task_initialization_task        (0x18)
#define image_3_initialization_task        (0x18)
#define image_3_start_task_us_tx_task_1st_wakeup_request        (0x720)
#define image_3_us_tx_task_1st_wakeup_request        (0x720)
#define image_3_us_tx_task_wakeup_request        (0x720)
#define image_3_start_task_epon_update_fifo_read_1st_wakeup_request        (0x1b44)
#define image_3_epon_update_fifo_read_1st_wakeup_request        (0x1b44)
#define image_3_start_task_epon_tx_task_wakeup_request        (0xdb4)
#define image_3_epon_tx_task_wakeup_request        (0xdb4)
#define image_3_start_task_budget_allocator_1st_wakeup_request        (0x10f4)
#define image_3_budget_allocator_1st_wakeup_request        (0x10f4)
#define image_3_start_task_debug_routine        (0x58)
#define image_3_debug_routine        (0x58)
#define image_3_start_task_gpon_control_wakeup_request        (0x58c)
#define image_3_gpon_control_wakeup_request        (0x58c)
#define image_3_start_task_ovl_budget_allocator_1st_wakeup_request        (0x1458)
#define image_3_ovl_budget_allocator_1st_wakeup_request        (0x1458)
#define image_3_start_task_flush_task_1st_wakeup_request        (0x17c8)
#define image_3_flush_task_1st_wakeup_request        (0x17c8)
#define image_3_start_task_update_fifo_us_read_1st_wakeup_request        (0x1a3c)
#define image_3_update_fifo_us_read_1st_wakeup_request        (0x1a3c)
#define image_3_debug_routine_handler        (0xc)
#define image_3_scheduling_update_status        (0xbb8)
#define image_3_scheduling_action_not_valid        (0xcb4)
#define image_3_basic_scheduler_update_dwrr        (0xf50)
#define image_3_complex_scheduler_update_dwrr_basic_schedulers        (0x10b0)
#define image_3_complex_scheduler_update_dwrr_complex_schedulers        (0x10c0)
#define image_3_complex_scheduler_update_dwrr_queues        (0x10d0)
#define image_3_basic_rate_limiter_complex_scheduler        (0x1518)
#define image_3_basic_rate_limiter_basic_scheduler_no_cs        (0x1550)
#define image_3_basic_rate_limiter_queue_with_cs_bs        (0x1584)
#define image_3_basic_rate_limiter_queue_with_bs        (0x15d8)
#define image_3_ovl_rate_limiter        (0x1614)
#define image_3_complex_rate_limiter_queue_sir        (0x1628)
#define image_3_complex_rate_limiter_queue_pir        (0x1664)
#define image_3_complex_rate_limiter_basic_scheduler_sir        (0x16a0)
#define image_3_complex_rate_limiter_basic_scheduler_pir        (0x16dc)

#endif

/* IMAGE 4 LABELS */
#ifndef IMAGE_4_CODE_ADDRESSES
#define IMAGE_4_CODE_ADDRESSES

#define image_4_start_task_initialization_task        (0x18)
#define image_4_initialization_task        (0x18)
#define image_4_start_task_processing_wakeup_request        (0xf68)
#define image_4_processing_wakeup_request        (0xf68)
#define image_4_start_task_debug_routine        (0x58)
#define image_4_debug_routine        (0x58)
#define image_4_start_task_dhd_tx_complete_wakeup_request        (0x5238)
#define image_4_dhd_tx_complete_wakeup_request        (0x5238)
#define image_4_start_task_dhd_rx_complete_wakeup_request        (0x5578)
#define image_4_dhd_rx_complete_wakeup_request        (0x5578)
#define image_4_debug_routine_handler        (0xc)
#define image_4_action_exception        (0x184)
#define image_4_processing_header_update_length_calc        (0x2b40)
#define image_4_processing_layer2_header_copy_30_bytes_8_bytes_align        (0x2c04)
#define image_4_processing_layer2_header_copy_22_bytes_8_bytes_align        (0x2c0c)
#define image_4_processing_layer2_header_copy_14_bytes_8_bytes_align        (0x2c14)
#define image_4_processing_layer2_header_copy_30_bytes_4_bytes_align        (0x2c28)
#define image_4_processing_layer2_header_copy_22_bytes_4_bytes_align        (0x2c38)
#define image_4_processing_layer2_header_copy_14_bytes_4_bytes_align        (0x2c48)
#define image_4_processing_layer2_header_copy_26_bytes_8_bytes_align        (0x2c68)
#define image_4_processing_layer2_header_copy_18_bytes_8_bytes_align        (0x2c74)
#define image_4_processing_layer2_header_copy_18_bytes_4_bytes_align        (0x2c98)
#define image_4_processing_layer2_header_copy_26_bytes_4_bytes_align        (0x2ca4)
#define image_4_tcam_cmd_ic_submit        (0x3cc0)
#define image_4_tcam_cmd_outer_tpid        (0x3d04)
#define image_4_tcam_cmd_inner_tpid        (0x3d1c)
#define image_4_tcam_cmd_ethertype        (0x3d34)
#define image_4_tcam_cmd_outer_vid        (0x3d4c)
#define image_4_tcam_cmd_inner_vid        (0x3d64)
#define image_4_tcam_cmd_outer_pbit        (0x3d7c)
#define image_4_tcam_cmd_inner_pbit        (0x3d94)
#define image_4_tcam_cmd_vlan_num        (0x3dac)
#define image_4_tcam_cmd_ip_protocol        (0x3dc4)
#define image_4_tcam_cmd_l3_protocol        (0x3ddc)
#define image_4_tcam_cmd_tos        (0x3df4)
#define image_4_tcam_cmd_network_layer        (0x3e0c)
#define image_4_tcam_cmd_ingress_port        (0x3e2c)
#define image_4_tcam_cmd_gem_flow        (0x3e44)
#define image_4_tcam_cmd_ipv6_label        (0x3e5c)
#define image_4_tcam_cmd_src_ip        (0x3e88)
#define image_4_tcam_cmd_src_ipv6_masked        (0x3edc)
#define image_4_tcam_cmd_dst_ip        (0x3f10)
#define image_4_tcam_cmd_dst_ipv6_masked        (0x3f64)
#define image_4_tcam_cmd_src_port        (0x3f98)
#define image_4_tcam_cmd_dst_port        (0x3fb0)
#define image_4_tcam_cmd_src_mac        (0x3fc8)
#define image_4_tcam_cmd_dst_mac        (0x3ff4)
#define image_4_tcam_cmd_generic_l2        (0x4020)
#define image_4_tcam_cmd_generic_l3        (0x4054)
#define image_4_tcam_cmd_generic_l4        (0x4088)
#define image_4_gpe_cmd_replace_16        (0x462c)
#define image_4_gpe_cmd_replace_32        (0x4634)
#define image_4_gpe_cmd_replace_bits_16        (0x464c)
#define image_4_gpe_cmd_copy_bits_16        (0x466c)
#define image_4_gpe_cmd_skip_if        (0x469c)
#define image_4_gpe_vlan_action_cmd_drop        (0x46bc)
#define image_4_gpe_vlan_action_cmd_dscp        (0x46c0)
#define image_4_gpe_vlan_action_cmd_mac_hdr_copy        (0x4710)

#endif

/* IMAGE 5 LABELS */
#ifndef IMAGE_5_CODE_ADDRESSES
#define IMAGE_5_CODE_ADDRESSES

#define image_5_start_task_initialization_task        (0x18)
#define image_5_initialization_task        (0x18)
#define image_5_start_task_processing_wakeup_request        (0xe3c)
#define image_5_processing_wakeup_request        (0xe3c)
#define image_5_start_task_budget_allocator_1st_wakeup_request        (0x582c)
#define image_5_budget_allocator_1st_wakeup_request        (0x582c)
#define image_5_start_task_debug_routine        (0x4e1c)
#define image_5_debug_routine        (0x4e1c)
#define image_5_start_task_service_queues_update_fifo_read_1st_wakeup_request        (0x5238)
#define image_5_service_queues_update_fifo_read_1st_wakeup_request        (0x5238)
#define image_5_start_task_service_queues_tx_task_wakeup_request        (0x52c8)
#define image_5_service_queues_tx_task_wakeup_request        (0x52c8)
#define image_5_debug_routine_handler        (0xc)
#define image_5_action_exception        (0x58)
#define image_5_processing_header_update_length_calc        (0x2a14)
#define image_5_processing_layer2_header_copy_30_bytes_8_bytes_align        (0x2ad8)
#define image_5_processing_layer2_header_copy_22_bytes_8_bytes_align        (0x2ae0)
#define image_5_processing_layer2_header_copy_14_bytes_8_bytes_align        (0x2ae8)
#define image_5_processing_layer2_header_copy_30_bytes_4_bytes_align        (0x2afc)
#define image_5_processing_layer2_header_copy_22_bytes_4_bytes_align        (0x2b0c)
#define image_5_processing_layer2_header_copy_14_bytes_4_bytes_align        (0x2b1c)
#define image_5_processing_layer2_header_copy_26_bytes_8_bytes_align        (0x2b3c)
#define image_5_processing_layer2_header_copy_18_bytes_8_bytes_align        (0x2b48)
#define image_5_processing_layer2_header_copy_18_bytes_4_bytes_align        (0x2b6c)
#define image_5_processing_layer2_header_copy_26_bytes_4_bytes_align        (0x2b78)
#define image_5_tcam_cmd_ic_submit        (0x3b94)
#define image_5_tcam_cmd_outer_tpid        (0x3bd8)
#define image_5_tcam_cmd_inner_tpid        (0x3bf0)
#define image_5_tcam_cmd_ethertype        (0x3c08)
#define image_5_tcam_cmd_outer_vid        (0x3c20)
#define image_5_tcam_cmd_inner_vid        (0x3c38)
#define image_5_tcam_cmd_outer_pbit        (0x3c50)
#define image_5_tcam_cmd_inner_pbit        (0x3c68)
#define image_5_tcam_cmd_vlan_num        (0x3c80)
#define image_5_tcam_cmd_ip_protocol        (0x3c98)
#define image_5_tcam_cmd_l3_protocol        (0x3cb0)
#define image_5_tcam_cmd_tos        (0x3cc8)
#define image_5_tcam_cmd_network_layer        (0x3ce0)
#define image_5_tcam_cmd_ingress_port        (0x3d00)
#define image_5_tcam_cmd_gem_flow        (0x3d18)
#define image_5_tcam_cmd_ipv6_label        (0x3d30)
#define image_5_tcam_cmd_src_ip        (0x3d5c)
#define image_5_tcam_cmd_src_ipv6_masked        (0x3db0)
#define image_5_tcam_cmd_dst_ip        (0x3de4)
#define image_5_tcam_cmd_dst_ipv6_masked        (0x3e38)
#define image_5_tcam_cmd_src_port        (0x3e6c)
#define image_5_tcam_cmd_dst_port        (0x3e84)
#define image_5_tcam_cmd_src_mac        (0x3e9c)
#define image_5_tcam_cmd_dst_mac        (0x3ec8)
#define image_5_tcam_cmd_generic_l2        (0x3ef4)
#define image_5_tcam_cmd_generic_l3        (0x3f28)
#define image_5_tcam_cmd_generic_l4        (0x3f5c)
#define image_5_gpe_cmd_replace_16        (0x4500)
#define image_5_gpe_cmd_replace_32        (0x4508)
#define image_5_gpe_cmd_replace_bits_16        (0x4520)
#define image_5_gpe_cmd_copy_bits_16        (0x4540)
#define image_5_gpe_cmd_skip_if        (0x4570)
#define image_5_gpe_vlan_action_cmd_drop        (0x4590)
#define image_5_gpe_vlan_action_cmd_dscp        (0x4594)
#define image_5_gpe_vlan_action_cmd_mac_hdr_copy        (0x45e4)
#define image_5_scheduling_service_queues_update_status        (0x53f4)
#define image_5_scheduling_service_queues_action_not_valid        (0x54d8)
#define image_5_complex_scheduler_update_dwrr_basic_schedulers        (0x5610)
#define image_5_complex_scheduler_update_dwrr_complex_schedulers        (0x5620)
#define image_5_complex_scheduler_update_dwrr_queues        (0x5630)
#define image_5_complex_rate_limiter_queue_sir        (0x5640)
#define image_5_complex_rate_limiter_queue_pir        (0x567c)
#define image_5_complex_rate_limiter_basic_scheduler_sir        (0x56b8)
#define image_5_complex_rate_limiter_basic_scheduler_pir        (0x56f4)
#define image_5_basic_rate_limiter_complex_scheduler        (0x5730)
#define image_5_basic_rate_limiter_basic_scheduler_no_cs        (0x5768)
#define image_5_basic_rate_limiter_queue_with_cs_bs        (0x579c)
#define image_5_basic_rate_limiter_queue_with_bs        (0x57f0)

#endif

/* IMAGE 6 LABELS */
#ifndef IMAGE_6_CODE_ADDRESSES
#define IMAGE_6_CODE_ADDRESSES

#define image_6_start_task_initialization_task        (0x18)
#define image_6_initialization_task        (0x18)
#define image_6_start_task_processing_wakeup_request        (0xe3c)
#define image_6_processing_wakeup_request        (0xe3c)
#define image_6_start_task_debug_routine        (0x4e1c)
#define image_6_debug_routine        (0x4e1c)
#define image_6_start_task_dhd_tx_post_wakeup_request        (0x56c8)
#define image_6_dhd_tx_post_wakeup_request        (0x56c8)
#define image_6_start_task_dhd_tx_post_update_fifo_wakeup_request        (0x5670)
#define image_6_dhd_tx_post_update_fifo_wakeup_request        (0x5670)
#define image_6_start_task_dhd_timer_1st_wakeup_request        (0x5238)
#define image_6_dhd_timer_1st_wakeup_request        (0x5238)
#define image_6_start_task_dhd_mcast_wakeup_request        (0x62f8)
#define image_6_dhd_mcast_wakeup_request        (0x62f8)
#define image_6_debug_routine_handler        (0xc)
#define image_6_action_exception        (0x58)
#define image_6_processing_header_update_length_calc        (0x2a14)
#define image_6_processing_layer2_header_copy_30_bytes_8_bytes_align        (0x2ad8)
#define image_6_processing_layer2_header_copy_22_bytes_8_bytes_align        (0x2ae0)
#define image_6_processing_layer2_header_copy_14_bytes_8_bytes_align        (0x2ae8)
#define image_6_processing_layer2_header_copy_30_bytes_4_bytes_align        (0x2afc)
#define image_6_processing_layer2_header_copy_22_bytes_4_bytes_align        (0x2b0c)
#define image_6_processing_layer2_header_copy_14_bytes_4_bytes_align        (0x2b1c)
#define image_6_processing_layer2_header_copy_26_bytes_8_bytes_align        (0x2b3c)
#define image_6_processing_layer2_header_copy_18_bytes_8_bytes_align        (0x2b48)
#define image_6_processing_layer2_header_copy_18_bytes_4_bytes_align        (0x2b6c)
#define image_6_processing_layer2_header_copy_26_bytes_4_bytes_align        (0x2b78)
#define image_6_tcam_cmd_ic_submit        (0x3b94)
#define image_6_tcam_cmd_outer_tpid        (0x3bd8)
#define image_6_tcam_cmd_inner_tpid        (0x3bf0)
#define image_6_tcam_cmd_ethertype        (0x3c08)
#define image_6_tcam_cmd_outer_vid        (0x3c20)
#define image_6_tcam_cmd_inner_vid        (0x3c38)
#define image_6_tcam_cmd_outer_pbit        (0x3c50)
#define image_6_tcam_cmd_inner_pbit        (0x3c68)
#define image_6_tcam_cmd_vlan_num        (0x3c80)
#define image_6_tcam_cmd_ip_protocol        (0x3c98)
#define image_6_tcam_cmd_l3_protocol        (0x3cb0)
#define image_6_tcam_cmd_tos        (0x3cc8)
#define image_6_tcam_cmd_network_layer        (0x3ce0)
#define image_6_tcam_cmd_ingress_port        (0x3d00)
#define image_6_tcam_cmd_gem_flow        (0x3d18)
#define image_6_tcam_cmd_ipv6_label        (0x3d30)
#define image_6_tcam_cmd_src_ip        (0x3d5c)
#define image_6_tcam_cmd_src_ipv6_masked        (0x3db0)
#define image_6_tcam_cmd_dst_ip        (0x3de4)
#define image_6_tcam_cmd_dst_ipv6_masked        (0x3e38)
#define image_6_tcam_cmd_src_port        (0x3e6c)
#define image_6_tcam_cmd_dst_port        (0x3e84)
#define image_6_tcam_cmd_src_mac        (0x3e9c)
#define image_6_tcam_cmd_dst_mac        (0x3ec8)
#define image_6_tcam_cmd_generic_l2        (0x3ef4)
#define image_6_tcam_cmd_generic_l3        (0x3f28)
#define image_6_tcam_cmd_generic_l4        (0x3f5c)
#define image_6_gpe_cmd_replace_16        (0x4500)
#define image_6_gpe_cmd_replace_32        (0x4508)
#define image_6_gpe_cmd_replace_bits_16        (0x4520)
#define image_6_gpe_cmd_copy_bits_16        (0x4540)
#define image_6_gpe_cmd_skip_if        (0x4570)
#define image_6_gpe_vlan_action_cmd_drop        (0x4590)
#define image_6_gpe_vlan_action_cmd_dscp        (0x4594)
#define image_6_gpe_vlan_action_cmd_mac_hdr_copy        (0x45e4)

#endif

/* IMAGE 7 LABELS */
#ifndef IMAGE_7_CODE_ADDRESSES
#define IMAGE_7_CODE_ADDRESSES

#define image_7_start_task_initialization_task        (0x18)
#define image_7_initialization_task        (0x18)
#define image_7_start_task_processing_wakeup_request        (0xe3c)
#define image_7_processing_wakeup_request        (0xe3c)
#define image_7_start_task_debug_routine        (0x4e1c)
#define image_7_debug_routine        (0x4e1c)
#define image_7_debug_routine_handler        (0xc)
#define image_7_action_exception        (0x58)
#define image_7_processing_header_update_length_calc        (0x2a14)
#define image_7_processing_layer2_header_copy_30_bytes_8_bytes_align        (0x2ad8)
#define image_7_processing_layer2_header_copy_22_bytes_8_bytes_align        (0x2ae0)
#define image_7_processing_layer2_header_copy_14_bytes_8_bytes_align        (0x2ae8)
#define image_7_processing_layer2_header_copy_30_bytes_4_bytes_align        (0x2afc)
#define image_7_processing_layer2_header_copy_22_bytes_4_bytes_align        (0x2b0c)
#define image_7_processing_layer2_header_copy_14_bytes_4_bytes_align        (0x2b1c)
#define image_7_processing_layer2_header_copy_26_bytes_8_bytes_align        (0x2b3c)
#define image_7_processing_layer2_header_copy_18_bytes_8_bytes_align        (0x2b48)
#define image_7_processing_layer2_header_copy_18_bytes_4_bytes_align        (0x2b6c)
#define image_7_processing_layer2_header_copy_26_bytes_4_bytes_align        (0x2b78)
#define image_7_tcam_cmd_ic_submit        (0x3b94)
#define image_7_tcam_cmd_outer_tpid        (0x3bd8)
#define image_7_tcam_cmd_inner_tpid        (0x3bf0)
#define image_7_tcam_cmd_ethertype        (0x3c08)
#define image_7_tcam_cmd_outer_vid        (0x3c20)
#define image_7_tcam_cmd_inner_vid        (0x3c38)
#define image_7_tcam_cmd_outer_pbit        (0x3c50)
#define image_7_tcam_cmd_inner_pbit        (0x3c68)
#define image_7_tcam_cmd_vlan_num        (0x3c80)
#define image_7_tcam_cmd_ip_protocol        (0x3c98)
#define image_7_tcam_cmd_l3_protocol        (0x3cb0)
#define image_7_tcam_cmd_tos        (0x3cc8)
#define image_7_tcam_cmd_network_layer        (0x3ce0)
#define image_7_tcam_cmd_ingress_port        (0x3d00)
#define image_7_tcam_cmd_gem_flow        (0x3d18)
#define image_7_tcam_cmd_ipv6_label        (0x3d30)
#define image_7_tcam_cmd_src_ip        (0x3d5c)
#define image_7_tcam_cmd_src_ipv6_masked        (0x3db0)
#define image_7_tcam_cmd_dst_ip        (0x3de4)
#define image_7_tcam_cmd_dst_ipv6_masked        (0x3e38)
#define image_7_tcam_cmd_src_port        (0x3e6c)
#define image_7_tcam_cmd_dst_port        (0x3e84)
#define image_7_tcam_cmd_src_mac        (0x3e9c)
#define image_7_tcam_cmd_dst_mac        (0x3ec8)
#define image_7_tcam_cmd_generic_l2        (0x3ef4)
#define image_7_tcam_cmd_generic_l3        (0x3f28)
#define image_7_tcam_cmd_generic_l4        (0x3f5c)
#define image_7_gpe_cmd_replace_16        (0x4500)
#define image_7_gpe_cmd_replace_32        (0x4508)
#define image_7_gpe_cmd_replace_bits_16        (0x4520)
#define image_7_gpe_cmd_copy_bits_16        (0x4540)
#define image_7_gpe_cmd_skip_if        (0x4570)
#define image_7_gpe_vlan_action_cmd_drop        (0x4590)
#define image_7_gpe_vlan_action_cmd_dscp        (0x4594)
#define image_7_gpe_vlan_action_cmd_mac_hdr_copy        (0x45e4)

#endif

/* COMMON LABELS */
#ifndef COMMON_CODE_ADDRESSES
#define COMMON_CODE_ADDRESSES

#define INVALID_LABEL_ADDRESS 0xFFFFFF

#define TCAM_CMD_DST_IP_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x3de4, 0x3f10, INVALID_LABEL_ADDRESS, 0x3f10, 0x3de4, 0x3de4, 0x3de4}
#define TCAM_CMD_DST_IPV6_MASKED_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x3e38, 0x3f64, INVALID_LABEL_ADDRESS, 0x3f64, 0x3e38, 0x3e38, 0x3e38}
#define TCAM_CMD_DST_MAC_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x3ec8, 0x3ff4, INVALID_LABEL_ADDRESS, 0x3ff4, 0x3ec8, 0x3ec8, 0x3ec8}
#define TCAM_CMD_DST_PORT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x3e84, 0x3fb0, INVALID_LABEL_ADDRESS, 0x3fb0, 0x3e84, 0x3e84, 0x3e84}
#define TCAM_CMD_ETHERTYPE_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x3c08, 0x3d34, INVALID_LABEL_ADDRESS, 0x3d34, 0x3c08, 0x3c08, 0x3c08}
#define TCAM_CMD_GEM_FLOW_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x3d18, 0x3e44, INVALID_LABEL_ADDRESS, 0x3e44, 0x3d18, 0x3d18, 0x3d18}
#define TCAM_CMD_GENERIC_L2_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x3ef4, 0x4020, INVALID_LABEL_ADDRESS, 0x4020, 0x3ef4, 0x3ef4, 0x3ef4}
#define TCAM_CMD_GENERIC_L3_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x3f28, 0x4054, INVALID_LABEL_ADDRESS, 0x4054, 0x3f28, 0x3f28, 0x3f28}
#define TCAM_CMD_GENERIC_L4_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x3f5c, 0x4088, INVALID_LABEL_ADDRESS, 0x4088, 0x3f5c, 0x3f5c, 0x3f5c}
#define TCAM_CMD_IC_SUBMIT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x3b94, 0x3cc0, INVALID_LABEL_ADDRESS, 0x3cc0, 0x3b94, 0x3b94, 0x3b94}
#define TCAM_CMD_INGRESS_PORT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x3d00, 0x3e2c, INVALID_LABEL_ADDRESS, 0x3e2c, 0x3d00, 0x3d00, 0x3d00}
#define TCAM_CMD_INNER_PBIT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x3c68, 0x3d94, INVALID_LABEL_ADDRESS, 0x3d94, 0x3c68, 0x3c68, 0x3c68}
#define TCAM_CMD_INNER_TPID_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x3bf0, 0x3d1c, INVALID_LABEL_ADDRESS, 0x3d1c, 0x3bf0, 0x3bf0, 0x3bf0}
#define TCAM_CMD_INNER_VID_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x3c38, 0x3d64, INVALID_LABEL_ADDRESS, 0x3d64, 0x3c38, 0x3c38, 0x3c38}
#define TCAM_CMD_IP_PROTOCOL_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x3c98, 0x3dc4, INVALID_LABEL_ADDRESS, 0x3dc4, 0x3c98, 0x3c98, 0x3c98}
#define TCAM_CMD_IPV6_LABEL_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x3d30, 0x3e5c, INVALID_LABEL_ADDRESS, 0x3e5c, 0x3d30, 0x3d30, 0x3d30}
#define TCAM_CMD_L3_PROTOCOL_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x3cb0, 0x3ddc, INVALID_LABEL_ADDRESS, 0x3ddc, 0x3cb0, 0x3cb0, 0x3cb0}
#define TCAM_CMD_NETWORK_LAYER_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x3ce0, 0x3e0c, INVALID_LABEL_ADDRESS, 0x3e0c, 0x3ce0, 0x3ce0, 0x3ce0}
#define TCAM_CMD_OUTER_PBIT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x3c50, 0x3d7c, INVALID_LABEL_ADDRESS, 0x3d7c, 0x3c50, 0x3c50, 0x3c50}
#define TCAM_CMD_OUTER_TPID_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x3bd8, 0x3d04, INVALID_LABEL_ADDRESS, 0x3d04, 0x3bd8, 0x3bd8, 0x3bd8}
#define TCAM_CMD_OUTER_VID_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x3c20, 0x3d4c, INVALID_LABEL_ADDRESS, 0x3d4c, 0x3c20, 0x3c20, 0x3c20}
#define TCAM_CMD_SRC_IP_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x3d5c, 0x3e88, INVALID_LABEL_ADDRESS, 0x3e88, 0x3d5c, 0x3d5c, 0x3d5c}
#define TCAM_CMD_SRC_IPV6_MASKED_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x3db0, 0x3edc, INVALID_LABEL_ADDRESS, 0x3edc, 0x3db0, 0x3db0, 0x3db0}
#define TCAM_CMD_SRC_MAC_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x3e9c, 0x3fc8, INVALID_LABEL_ADDRESS, 0x3fc8, 0x3e9c, 0x3e9c, 0x3e9c}
#define TCAM_CMD_SRC_PORT_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x3e6c, 0x3f98, INVALID_LABEL_ADDRESS, 0x3f98, 0x3e6c, 0x3e6c, 0x3e6c}
#define TCAM_CMD_TOS_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x3cc8, 0x3df4, INVALID_LABEL_ADDRESS, 0x3df4, 0x3cc8, 0x3cc8, 0x3cc8}
#define TCAM_CMD_VLAN_NUM_ADDR_ARR {INVALID_LABEL_ADDRESS, 0x3c80, 0x3dac, INVALID_LABEL_ADDRESS, 0x3dac, 0x3c80, 0x3c80, 0x3c80}

#endif

