dynamic: install


all: install


install:
	cp -f nvram_params_TP6750.save $(INSTALL_DIR)/etc/wlan/nvram_params
	cp -f nvramUpdate_TP6750.save $(INSTALL_DIR)/bin/nvramUpdate
	cp -f wlssk_TP6750.save $(INSTALL_DIR)/bin/wlssk
	cp -f libnvram.so_TP6750.save $(INSTALL_DIR)/lib/libnvram.so
