#ifndef RUNNER_D_CODE_ADDRESSES
#define RUNNER_D_CODE_ADDRESSES

#define runner_d_start_task_initialization_task		(0x14)
#define runner_d_initialization_task		(0x14)
#define runner_d_start_task_timer_scheduler_set		(0x1A8C)
#define runner_d_timer_scheduler_set		(0x1A8C)
#define runner_d_start_task_flow_cache_wakeup_request		(0xC40)
#define runner_d_flow_cache_wakeup_request		(0xC40)
#define runner_d_start_task_lan_dispatch_wakeup_request		(0x1844)
#define runner_d_lan_dispatch_wakeup_request		(0x1844)
#define runner_d_start_task_lan_cpu_wakeup_request		(0x154)
#define runner_d_lan_cpu_wakeup_request		(0x154)
#define runner_d_start_task_debug_routine		(0x6C)
#define runner_d_debug_routine		(0x6C)
#define runner_d_start_task_free_skb_index_wakeup_request		(0x1C08)
#define runner_d_free_skb_index_wakeup_request		(0x1C08)
#define runner_d_free_skb_index_tx_abs_done		(0x1C08)
#define runner_d_start_task_dhd_rx_complete_wakeup_request		(0x1CDC)
#define runner_d_dhd_rx_complete_wakeup_request		(0x1CDC)
#define runner_d_gpe_sop_push_replace_ddr_sram_32		(0x1200)
#define runner_d_gpe_sop_push_replace_sram_32_64		(0x1270)
#define runner_d_gpe_sop_push_replace_sram_64		(0x1284)
#define runner_d_gpe_sop_push_replace_sram_64_32		(0x1298)
#define runner_d_gpe_sop_pull_replace_ddr_sram_32		(0x12AC)
#define runner_d_gpe_sop_pull_replace_sram_32_64		(0x131C)
#define runner_d_gpe_sop_pull_replace_sram_64		(0x136C)
#define runner_d_gpe_sop_pull_replace_sram_64_32		(0x13A8)
#define runner_d_gpe_replace_pointer_32_ddr		(0x13F8)
#define runner_d_gpe_replace_pointer_32_sram		(0x141C)
#define runner_d_gpe_replace_pointer_64_sram		(0x1440)
#define runner_d_gpe_replace_16		(0x1464)
#define runner_d_gpe_replace_32		(0x1498)
#define runner_d_gpe_replace_bits_16		(0x14BC)
#define runner_d_gpe_copy_add_16_cl		(0x14E8)
#define runner_d_gpe_copy_add_16_sram		(0x14F4)
#define runner_d_gpe_copy_bits_16_cl		(0x153C)
#define runner_d_gpe_copy_bits_16_sram		(0x1548)
#define runner_d_gpe_insert_16		(0x1590)
#define runner_d_gpe_delete_16		(0x15F8)
#define runner_d_gpe_decrement_8		(0x1638)
#define runner_d_gpe_apply_icsum_16		(0x165C)
#define runner_d_gpe_apply_icsum_nz_16		(0x1680)
#define runner_d_gpe_compute_csum_16_cl		(0x16BC)
#define runner_d_gpe_compute_csum_16_sram		(0x16C8)
#define runner_d_gpe_buffer_copy_16_sram		(0x1708)
#define runner_d_gpe_buffer_copy_16_ddr		(0x1730)
#define runner_d_upstream_ingress_rate_limiter_budget_allocate		(0x1B0C)
#define runner_d_upstream_quasi_budget_allocate		(0x1B8C)
#define runner_d_schedule_free_skb_index		(0x1BEC)

#endif
