#ifndef RUNNER_D_CODE_ADDRESSES
#define RUNNER_D_CODE_ADDRESSES

#define runner_d_start_task_initialization_task		(0x14)
#define runner_d_initialization_task		(0x14)
#define runner_d_start_task_timer_scheduler_set		(0x1A64)
#define runner_d_timer_scheduler_set		(0x1A64)
#define runner_d_start_task_flow_cache_wakeup_request		(0xBE8)
#define runner_d_flow_cache_wakeup_request		(0xBE8)
#define runner_d_start_task_lan_dispatch_wakeup_request		(0x17CC)
#define runner_d_lan_dispatch_wakeup_request		(0x17CC)
#define runner_d_start_task_debug_routine		(0x6C)
#define runner_d_debug_routine		(0x6C)
#define runner_d_start_task_free_skb_index_wakeup_request		(0x1BE0)
#define runner_d_free_skb_index_wakeup_request		(0x1BE0)
#define runner_d_free_skb_index_tx_abs_done		(0x1BE0)
#define runner_d_gpe_sop_push_replace_ddr_sram_32		(0x1188)
#define runner_d_gpe_sop_push_replace_sram_32_64		(0x11F8)
#define runner_d_gpe_sop_push_replace_sram_64		(0x120C)
#define runner_d_gpe_sop_push_replace_sram_64_32		(0x1220)
#define runner_d_gpe_sop_pull_replace_ddr_sram_32		(0x1234)
#define runner_d_gpe_sop_pull_replace_sram_32_64		(0x12A4)
#define runner_d_gpe_sop_pull_replace_sram_64		(0x12F4)
#define runner_d_gpe_sop_pull_replace_sram_64_32		(0x1330)
#define runner_d_gpe_replace_pointer_32_ddr		(0x1380)
#define runner_d_gpe_replace_pointer_32_sram		(0x13A4)
#define runner_d_gpe_replace_pointer_64_sram		(0x13C8)
#define runner_d_gpe_replace_16		(0x13EC)
#define runner_d_gpe_replace_32		(0x1420)
#define runner_d_gpe_replace_bits_16		(0x1444)
#define runner_d_gpe_copy_add_16_cl		(0x1470)
#define runner_d_gpe_copy_add_16_sram		(0x147C)
#define runner_d_gpe_copy_bits_16_cl		(0x14C4)
#define runner_d_gpe_copy_bits_16_sram		(0x14D0)
#define runner_d_gpe_insert_16		(0x1518)
#define runner_d_gpe_delete_16		(0x1580)
#define runner_d_gpe_decrement_8		(0x15C0)
#define runner_d_gpe_apply_icsum_16		(0x15E4)
#define runner_d_gpe_apply_icsum_nz_16		(0x1608)
#define runner_d_gpe_compute_csum_16_cl		(0x1644)
#define runner_d_gpe_compute_csum_16_sram		(0x1650)
#define runner_d_gpe_buffer_copy_16_sram		(0x1690)
#define runner_d_gpe_buffer_copy_16_ddr		(0x16B8)
#define runner_d_upstream_ingress_rate_limiter_budget_allocate		(0x1AE4)
#define runner_d_upstream_quasi_budget_allocate		(0x1B64)
#define runner_d_schedule_free_skb_index		(0x1BC4)

#endif
